// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Place defines model for place.
type Place struct {
	Id        openapi_types.UUID `json:"id"`
	ImageUrl  *string            `json:"image_url,omitempty"`
	Latitude  float32            `json:"latitude"`
	Longitude float32            `json:"longitude"`
	Name      string             `json:"name"`
	ReviewUrl *string            `json:"review_url,omitempty"`
	Type      string             `json:"type"`
}
