// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoffeeMapItem struct {
	ID          string
	ItemName    string
	ItemType    pgtype.Text
	ImageUrl    pgtype.Text
	ReviewUrl   pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
