// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type CoffeeMapItem struct {
	ID        string
	Name      string
	ItemType  sql.NullString
	ImageUrl  sql.NullString
	ReviewUrl sql.NullString
}
