// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO coffee_map_item (
    id,
    item_name,
    item_type,
    image_url,
    review_url,
    summary
) VALUES (
    gen_random_uuid(),
    $1, $2, $3, $4, $5
) RETURNING id, item_name, item_type, image_url, review_url, summary, created_at, updated_at
`

type CreateItemParams struct {
	ItemName  string
	ItemType  pgtype.Text
	ImageUrl  pgtype.Text
	ReviewUrl pgtype.Text
	Summary   pgtype.Text
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CoffeeMapItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ItemName,
		arg.ItemType,
		arg.ImageUrl,
		arg.ReviewUrl,
		arg.Summary,
	)
	var i CoffeeMapItem
	err := row.Scan(
		&i.ID,
		&i.ItemName,
		&i.ItemType,
		&i.ImageUrl,
		&i.ReviewUrl,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, item_name, item_type, image_url, review_url, summary, created_at, updated_at FROM coffee_map_item
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (CoffeeMapItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i CoffeeMapItem
	err := row.Scan(
		&i.ID,
		&i.ItemName,
		&i.ItemType,
		&i.ImageUrl,
		&i.ReviewUrl,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, item_name, item_type, image_url, review_url, summary, created_at, updated_at FROM coffee_map_item
ORDER BY id
`

func (q *Queries) ListItems(ctx context.Context) ([]CoffeeMapItem, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoffeeMapItem
	for rows.Next() {
		var i CoffeeMapItem
		if err := rows.Scan(
			&i.ID,
			&i.ItemName,
			&i.ItemType,
			&i.ImageUrl,
			&i.ReviewUrl,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
