// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getItem = `-- name: GetItem :one
SELECT id, name, item_type, image_url, review_url FROM coffee_map_item
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id string) (CoffeeMapItem, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i CoffeeMapItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.ImageUrl,
		&i.ReviewUrl,
	)
	return i, err
}
