name: Verify frontend build
on:
  pull_request:
    paths:
      - frontend/**
jobs:
  frontend-verify-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install
        working-directory: frontend
        run: yarn install
      - name: Test
        working-directory: frontend
        run: yarn astro check
  frontend-verify-apilib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install
        working-directory: frontend
        run: yarn install
      - name: Check generated API code
        working-directory: frontend
        run: yarn run check-api
