name: Verify backend build
on:
  pull_request:
    paths:
      - cmd/**
      - db/**
      - internal/**
      - pkg/**
jobs:
  frontend-verify-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
